### ISSUE TITLE
show logs of skipped only

### ISSUE THREAD

**Issue by revelt** [VladimirMikulic/parcel-resolver-ignore#1]
hi Vladimir! Thank you for this awesome plugin. I noticed the plugin also shows logs in cases where it didn't exclude: 

![logs](https://user-images.githubusercontent.com/8344688/123846736-a6bae300-d90d-11eb-96c9-3c661ff4d57b.png)

What if we logged only if `shouldExcludeFile` is `true`?

https://github.com/VladimirMikulic/parcel-resolver-ignore/blob/b52182e347e3779fed5b29db1ec6b6bcb0d8560d/lib/index.js#L15

That should reduce the log footprint. What do you think?

**Comment by revelt** [comment]
Or we could maybe format it nicer altogether, to make more informative to user — the boolean is not very clear...

If you approve this feature but you're busy, I can raise a PR. 👍

**Comment by VladimirMikulic** [comment]
Good point @revelt. It should definitely be more clearer. If you have some spare time, feel free to raise a PR and I'll gladly merge it!

**Comment by revelt** [comment]
https://github.com/VladimirMikulic/parcel-resolver-ignore/pull/3
