### ISSUE TITLE
`<script type="module">` tags are rewritten even when ignored

### ISSUE THREAD

**Issue by sabberworm** [VladimirMikulic/parcel-resolver-ignore#11]
Thanks for this plugin. I think it’s mostly what I’m looking for except that it doesn’t prevent parcel from transforming the tags referencing an ignored import in HTML.

Example:

```html
<script
	type="module"
	src="some-es-module.js"
></script>
```

with `"parcelIgnore"` set to `["some-es-module\\.js"]` will correctly output:

```
console: Skipped some-es-module.js
```

but the resulting HTML will still have its script tag transformed to:

```
<script src="some-es-module.js" defer=""></script>
```

(note the missing `type="module"` and added `defer` attributes). Is there any way to get parcel to leave the entire tag alone?

**Comment by VladimirMikulic** [comment]
Hi @sabberworm! Parcel automatically modifies attributes.
https://parceljs.org/languages/html/#scripts

**Comment by sabberworm** [comment]
Ah, that’s too bad.
