### ISSUE TITLE
Better config loading

### ISSUE THREAD

**Issue by mischnic** [VladimirMikulic/parcel-resolver-ignore#13]
The current approach doesn't properly invalidate the cache when changing the ignore list.

The intended way is by using `loadConfig`, as used by the default resovler:
https://github.com/parcel-bundler/parcel/blob/d1d24bf2bda29b23f7351548fa0e3cbf93983acb/packages/resolvers/default/src/DefaultResolver.js#L11-L14

**Comment by VladimirMikulic** [comment]
Thanks @mischnic! Fixed.
